import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Hulu clone generated by create next app" />
        <link rel="icon" href="/hulu.ico" />
      </Head>
      
      {/* Header */}
      <Header />
      
      {/* Nav */}

      {/* Results */}
    </div>
  )
}
